name: transitToJobs_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - geopandas
  - pandas
  - r5py
  - contextily
  - rasterio
  - folium
  - matplotlib
  - numpy
  - scipy
  - pip
  - pip:
    - pygris